spring:
  application:
    name: security

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

